### ISSUE TITLE
pip install dumb-initdumb-init-1.2.5.post1 version

### ISSUE THREAD

**Issue by liord150** [Yelp/dumb-init#275]
OS: ubuntu:20.04

Error:

```
 Collecting dumb-init
   Downloading https://files.pythonhosted.org/packages/3d/a6/73c6e478115f98f5778e8b7808dc59d0985eae178b4c38da72968887a13e/dumb-init-1.2.5.post1.tar.gz
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-1aPBGh/dumb-init/setup.py", line 90
         print('supports -static... ', end='')
                                          ^
     SyntaxError: invalid syntax
     
     ----------------------------------------
 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1aPBGh/dumb-init/
```

**Comment by asottile** [comment]
dumb-init's distribution requires python 3 -- you're installing using python 2
